### ISSUE TITLE
SERVO42B

### ISSUE THREAD

**Issue by np22-jpg** [makerbase-mks/MKS-SERVO42A#2]
Hey, can you show the SERVO42B schematics and the such? Really curious to see what it's rocking

**Comment by 3DSmitty** [comment]
Yes I would like to know the source code is available for upgrades before I purchase them.

**Comment by makerbase-mks** [comment]
You can refer to： https://github.com/makerbase-mks/MKS-SERVO42B

**Comment by GsmZolika** [comment]
Hi! Can I have firmware for 42B board? I'm kill the stm32 cpu. I have a new cpu only the firmware missing.
Thanks!

**Comment by MS1987** [comment]
@GsmZolika , 42B Board's firmware has been open source, you can check it in the makerbase github.
