### ISSUE TITLE
Marlin 2.0.x configuration ...

### ISSUE THREAD

**Issue by themacboy** [makerbase-mks/MKS-SERVO42A#7]
How can I correctly config this drive in Marlin?

**Comment by makerbase-mks** [comment]
Hi! You need't config drive type and can use it directly.

**Comment by themacboy** [comment]
what type? Im not sure. The list of optiosn is short and Im not sure the exact parameter to set. Thx in advance

**Comment by makerbase-mks** [comment]
You can use it directly.
